# Generated by Django 4.2.5 on 2023-09-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
